var Layout=function(){var isRTL=false;var isIE8=false;var isIE9=false;var isIE10=false;var isIE11=false;var responsive=true;var responsiveHandlers=[];var handleInit=function(){if($('body').css('direction')==='rtl'){isRTL=true;}
isIE8=!!navigator.userAgent.match(/MSIE 8.0/);isIE9=!!navigator.userAgent.match(/MSIE 9.0/);isIE10=!!navigator.userAgent.match(/MSIE 10.0/);isIE11=!!navigator.userAgent.match(/MSIE 11.0/);if(isIE10){jQuery('html').addClass('ie10');}
if(isIE11){jQuery('html').addClass('ie11');}}
var runResponsiveHandlers=function(){for(var i in responsiveHandlers){var each=responsiveHandlers[i];each.call();}}
var handleResponsiveOnResize=function(){var resize;if(isIE8){var currheight;$(window).resize(function(){if(currheight==document.documentElement.clientHeight){return;}
if(resize){clearTimeout(resize);}
resize=setTimeout(function(){runResponsiveHandlers();},50);currheight=document.documentElement.clientHeight;});}else{$(window).resize(function(){if(resize){clearTimeout(resize);}
resize=setTimeout(function(){runResponsiveHandlers();},50);});}}
var handleIEFixes=function(){if(isIE8||isIE9){jQuery('input[placeholder]:not(.placeholder-no-fix), textarea[placeholder]:not(.placeholder-no-fix)').each(function(){var input=jQuery(this);if(input.val()==''&&input.attr("placeholder")!=''){input.addClass("placeholder").val(input.attr('placeholder'));}
input.focus(function(){if(input.val()==input.attr('placeholder')){input.val('');}});input.blur(function(){if(input.val()==''||input.val()==input.attr('placeholder')){input.val(input.attr('placeholder'));}});});}}
var handleScrollers=function(){$('.scroller').each(function(){var height;if($(this).attr("data-height")){height=$(this).attr("data-height");}else{height=$(this).css('height');}
$(this).slimScroll({allowPageScroll:true,size:'7px',color:($(this).attr("data-handle-color")?$(this).attr("data-handle-color"):'#bbb'),railColor:($(this).attr("data-rail-color")?$(this).attr("data-rail-color"):'#eaeaea'),position:isRTL?'left':'right',height:height,alwaysVisible:($(this).attr("data-always-visible")=="1"?true:false),railVisible:($(this).attr("data-rail-visible")=="1"?true:false),disableFadeOut:true});});}
var handleSearch=function(){$('.search-btn').click(function(){if($('.search-btn').hasClass('show-search-icon')){if($(window).width()>767){$('.search-box').fadeOut(300);}else{$('.search-box').fadeOut(0);}
$('.search-btn').removeClass('show-search-icon');}else{if($(window).width()>767){$('.search-box').fadeIn(300);}else{$('.search-box').fadeIn(0);}
$('.search-btn').addClass('show-search-icon');}});if($('.search-btn').size()!=0){$('.search-box, .search-btn').on('click',function(e){e.stopPropagation();});$('body').on('click',function(){if($('.search-btn').hasClass('show-search-icon')){$('.search-btn').removeClass("show-search-icon");$('.search-box').fadeOut(300);}});}}
var handleMenu=function(){$(".header .navbar-toggle").click(function(){if($(".header .navbar-collapse").hasClass("open")){$(".header .navbar-collapse").slideDown(300).removeClass("open");}else{$(".header .navbar-collapse").slideDown(300).addClass("open");}});}
var handleSubMenuExt=function(){$(".header-navigation .dropdown").on("hover",function(){if($(this).children(".header-navigation-content-ext").show()){if($(".header-navigation-content-ext").height()>=$(".header-navigation-description").height()){$(".header-navigation-description").css("height",$(".header-navigation-content-ext").height()+22);}}});}
var handleSidebarMenu=function(){$(".sidebar .dropdown > a").click(function(event){if($(this).next().hasClass('dropdown-menu')){event.preventDefault();if($(this).hasClass("collapsed")==false){$(this).addClass("collapsed");$(this).siblings(".dropdown-menu").slideDown(300);}else{$(this).removeClass("collapsed");$(this).siblings(".dropdown-menu").slideUp(300);}}});}
function handleDifInits(){$(".header .navbar-toggle span:nth-child(2)").addClass("short-icon-bar");$(".header .navbar-toggle span:nth-child(4)").addClass("short-icon-bar");}
function handleUniform(){if(!jQuery().uniform){return;}
var test=$("input[type=checkbox]:not(.toggle), input[type=radio]:not(.toggle, .star)");if(test.size()>0){test.each(function(){if($(this).parents(".checker").size()==0){$(this).show();$(this).uniform();}});}}
var handleFancybox=function(){if(!jQuery.fancybox){return;}
jQuery(".fancybox-fast-view").fancybox();if(jQuery(".fancybox-button").size()>0){jQuery(".fancybox-button").fancybox({groupAttr:'data-rel',prevEffect:'none',nextEffect:'none',closeBtn:true,helpers:{title:{type:'inside'}}});$('.fancybox-video').fancybox({type:'iframe'});}}
var handleAccordions=function(){jQuery('body').on('shown.bs.collapse','.accordion.scrollable',function(e){Layout.scrollTo($(e.target),-100);});}
var handleTabs=function(){$('body').on('shown.bs.tab','.nav.nav-tabs',function(){handleSidebarAndContentHeight();});if(location.hash){var tabid=location.hash.substr(1);$('a[href="#'+tabid+'"]').click();}}
var handleMobiToggler=function(){$(".mobi-toggler").on("click",function(event){event.preventDefault();$(".header").toggleClass("menuOpened");$(".header").find(".header-navigation").toggle(300);});}
var handleTheme=function(){var panel=$('.color-panel');var setColor=function(color){$('#style-color').attr("href","assets/corporate/css/themes/"+color+".css");$('.corporate .site-logo img').attr("src","assets/corporate/img/logos/logo-corp-"+color+".png");$('.ecommerce .site-logo img').attr("src","assets/corporate/img/logos/logo-shop-"+color+".png");}
$('.icon-color',panel).click(function(){$('.color-mode').show();$('.icon-color-close').show();});$('.icon-color-close',panel).click(function(){$('.color-mode').hide();$('.icon-color-close').hide();});$('li',panel).click(function(){var color=$(this).attr("data-style");setColor(color);$('.inline li',panel).removeClass("current");$(this).addClass("current");});}
return{init:function(){handleTheme();handleInit();handleResponsiveOnResize();handleIEFixes();handleSearch();handleFancybox();handleDifInits();handleSidebarMenu();handleAccordions();handleMenu();handleScrollers();handleSubMenuExt();handleMobiToggler();},initUniform:function(els){if(els){jQuery(els).each(function(){if($(this).parents(".checker").size()==0){$(this).show();$(this).uniform();}});}else{handleUniform();}},initFacebook:function(){!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk');},initTouchspin:function(){$(".product-quantity .form-control").TouchSpin({buttondown_class:"btn quantity-down",buttonup_class:"btn quantity-up"});$(".quantity-down").html("<i class='fa fa-angle-down'></i>");$(".quantity-up").html("<i class='fa fa-angle-up'></i>");},initFixHeaderWithPreHeader:function(){jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>37){jQuery("body").addClass("page-header-fixed");}
else{jQuery("body").removeClass("page-header-fixed");}});},initNavScrolling:function(){function NavScrolling(){if(jQuery(window).scrollTop()>60){jQuery(".header").addClass("reduce-header");}
else{jQuery(".header").removeClass("reduce-header");}}
NavScrolling();jQuery(window).scroll(function(){NavScrolling();});},initImageZoom:function(){$('.product-main-image').zoom({url:$('.product-main-image img').attr('data-BigImgSrc')});},initSliderRange:function(){$("#slider-range").slider({range:true,min:0,max:500,values:[50,250],slide:function(event,ui){$("#amount").val("$"+ui.values[0]+" - $"+ui.values[1]);}});$("#amount").val("$"+$("#slider-range").slider("values",0)+
" - $"+$("#slider-range").slider("values",1));},scrollTo:function(el,offeset){var pos=(el&&el.size()>0)?el.offset().top:0;if(el){if($('body').hasClass('page-header-fixed')){pos=pos-$('.header').height();}
pos=pos+(offeset?offeset:-1*el.height());}
jQuery('html,body').animate({scrollTop:pos},'slow');},addResponsiveHandler:function(func){responsiveHandlers.push(func);},scrollTop:function(){App.scrollTo();},gridOption1:function(){$(function(){$('.grid-v1').mixitup();});}};}();